# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    paths:
      - "client/*"
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    name: React Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pathing to correct directory and install dependencies
        run: |
          npm run install-client
          npm test
